import numpy as np
a=np.arange(1,49).reshape(8,3,2,1)
b=np.arange(1,36).reshape(7,1,5)
print(a)
print("$"*30)
print(b)
# print("$"*30)
# c=(a*b)
# print(c)
# print("$"*30)
# print(a.ndim)
# print(b.ndim)
# print(c.ndim)
# print(a.nbytes)
# print(b.nbytes)
# print(c.nbytes)
# print(a*b*c)