import numpy as np
a=np.array([1,2,3,4],dtype=int)
print(np.shape(a))
print("=============")
b=np.array([5,6,7],dtype=int)
print(np.shape(b))
print("==============")
print("Vector",a[:])

print("b's Vector",b[:])
print("==========================")
a1=(a[:,np.newaxis])
print(a1)
print(np.ndim(a1))
print(np.shape(a1))
print("++++++++++++++++++++")
b1=(b[np.newaxis,:])
print(b1)
print(np.ndim(b1))
print(np.shape(b1))
