import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]],order='C',dtype=np.int16)
print(a)
print(id(a))
print("=================")
view1=a.view(np.int16)
print(view1)
print(type(view1))
print("====================")
print(a)
print("====================")
view1[1][2]=50
print(view1)
print(type(view1))
print(a)